### ISSUE TITLE
Enquiry about the last question

### ISSUE THREAD

**Issue by YiyangGao** [dataanalysis3/assignment2#1]
Hi Alexey,

The last question is:
2) Select only couples that are ethnically endogamous (i.e. partners come from the same ethnic group) for the following groups: White British, Indian, and Pakistani.
I am wondering whether couples here are heterosexual couples same as the previous questions, or including all types of partners?

Many thanks.

**Comment by abessudnov** [comment]
Yes, heterosexual couples only.
