### ISSUE TITLE
Clarification with question wording

### ISSUE THREAD

**Issue by hd371** [dataanalysis3/assignment2#2]
Please could I have clarification and expansion on what the wording of "4) ...What could affect your findings?" means for the final question of assignment 2? Many thanks.

**Comment by abessudnov** [comment]
Which factors could contribute to the observed differences in the number of children in the household by ethnic group.

**Comment by hd371** [comment]
In terms of methodological factors/data limitations regarding how the data is collected for Understanding Society, or broader societal factors that explain the observed differences? Or both?

**Comment by abessudnov** [comment]
Both, but keep it brief and focussed. There will be one factor (that you could call methodological) that is particularly important.

**Comment by hd371** [comment]
Many thanks for the clarifications.
